// constants/adminConstants.js
export const ADMIN_VEHICLES_ON_SALE_REQUEST = "ADMIN_VEHICLES_ON_SALE_REQUEST";
export const ADMIN_VEHICLES_ON_SALE_SUCCESS = "ADMIN_VEHICLES_ON_SALE_SUCCESS";
export const ADMIN_VEHICLES_ON_SALE_FAIL = "ADMIN_VEHICLES_ON_SALE_FAIL";
